name: books

services:
  backend:
    build:
      context: ../../
      dockerfile: deployments/dev/backend/Dockerfile
      tags:
        - "books-backend:dev"
    container_name: books-backend
    volumes:
      - ../..:/app
      - backend-data:/run/app
    ports:
      - 8000:8000
    depends_on:
      keycloak:
        condition: service_healthy
    command: books-fastapi-dev

  keycloak:
    image: keycloak/keycloak:26.2.2
    container_name: books-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_PASSWORD: root
      KC_BOOTSTRAP_ADMIN_USERNAME: root
      KC_HEALTH_ENABLED: true
      KC_FEATURES: preview
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak:/mnt
    entrypoint: [""]
    command: bash /mnt/start.sh
    ports:
      - 8080:8080
    healthcheck:
      test: bash /mnt/healthcheck.sh
      start_period: 5m
      start_interval: 3s
      interval: 10s

volumes:
  backend-data: null

  keycloak-data:
    labels:
      db: true
