name: books

services:
  backend:
    build:
      context: ../../
      dockerfile: deployments/dev/backend/Dockerfile
      tags:
        - "books-backend:dev"
    container_name: books-backend
    volumes:
      - ../..:/app
      - backend-data:/run/app
    ports:
      - 8000:8000
    command: books-fastapi-dev

volumes:
  backend-data: null
