name: books

services:
  backend:
    build:
      context: ../../
      dockerfile: deployments/dev/backend/Dockerfile
      tags:
        - "books-backend:dev"
    container_name: books-backend
    volumes:
      - ../..:/app
      - backend-data:/run/app
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      JWT_SECRET: super-secret-jwt-secret
      POSTGRES_URL: postgresql+psycopg://root:root@postgres/root
    command: books-fastapi-dev

  postgres:
    image: postgres:16.3-alpine3.19
    container_name: books-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: pg_isready -d root -U root
      start_period: 1m
      start_interval: 1s
      interval: 5s

  keycloak:
    image: keycloak/keycloak:26.2.2
    container_name: books-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_PASSWORD: root
      KC_BOOTSTRAP_ADMIN_USERNAME: root
      KC_HEALTH_ENABLED: true
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: start-dev
    ports:
      - 8080:8080

volumes:
  backend-data: null

  postgres-data:
    labels:
      db: true

  keycloak-data:
    labels:
      db: true
