name: books

services:
  backend:
    build:
      context: ../../
      dockerfile: deployments/dev/backend/Dockerfile
      tags:
        - "books-backend:dev"
    container_name: books-backend
    volumes:
      - ../..:/app
      - backend-data:/run/app
    environment:
      JWT_SECRET: super-secret-jwt-secret
      JWT_SECRET: super-secret-jwt-secret
      TELEGRAM_SECRETS_FILE_PATH: /app/deployments/dev/backend/tg_secrets.toml
    ports:
      - 8000:8000
    command: books-fastapi-dev

volumes:
  backend-data: null
